# Токен для телеграма, полученный от BotFather
token: "<Токен>"

# Имена бота. Бот будет реагировать, если обращаться к нему по этим именам.
# Так же необходимы чтобы бота было нельзя заставить дежурить XD
botNames:
  - "@ProdskyOlegOlegovich_bot"
  - "Олег"

# Cron-выражение для запуска джобы по смене дежурного.

# Выражение учитывает секунды и работает по Гринвичу,
# так что необходимо добавлять спереди еще 0 и к часам надо прибавлять 3 (если для Москвы)
# https://insanusmokrassar.github.io/KrontabPredictor

# 0 30 6 * * - каждый день в 9:30 по мск
switchAttendantCron: "0 30 6 * *"
